```{r}
numeric.glm <- glm(approved ~ . + self:(odir + white + uria), data = df, family = binomial)
model <- numeric.glm
N <- nrow(df)
```


``` {r}
res_deviance <- residuals(model, type = 'deviance')

neg_res <- res_deviance[res_deviance < 0]
pos_res <- res_deviance[res_deviance > 0]

ggplot(data.frame(res_deviance), aes(x = res_deviance)) +
  geom_histogram(binwidth = 0.1, fill = "steelblue", color = "black") +
  labs(x = "Deviance Residuals", y = "Count") +
  theme_bw()
```
Cook's Distance
```{r}
model <- numeric.glm

# Cook's Distance
cooksdf <- as.data.frame(cooks.distance(model))
names(cooksdf) <- "cooksd"
cooksdf$approved <- as.factor(df$approved)

cutoff  <- round(8/(N - 2 * length(model$coefficients)), 4)

plot1 <- ggplot(cooksdf, aes(x = seq(1:length(cooksd)), y = cooksd, col = approved)) +
  geom_point() +
  labs(x = "Observation", y = "Cook's Distance") 

plot1 + geom_hline(aes(yintercept=cutoff)) + 
  scale_y_continuous(breaks=sort(c(ggplot_build(plot1)$layout$panel_ranges[[1]]$y.major_source, cutoff))) +
  theme_bw()

```

``` {r}
# Total exceeding cutoff
cat('exceeding cutoff',cooksdf$approved[cooksdf$cooksd > cutoff] %>% table(), '\n')

# Approved distribution ratio
cat('approved ratio', df$approved %>% table() %>% prop.table(), '\n')

# Biggest outlier
cat('most outlying observation (according to cooks distance)',which.max(cooksdf$cooksd))
```

Code used for the appendix: Removing outliers
``` {r}
outliers <- cooksdf %>% arrange(desc(cooksd)) %>% dplyr::slice_head(n = 62)
remove_idx <- as.numeric(rownames(outliers))

df_noo <- df[-remove_idx,]
test.glm <- glm(approved ~ . + self:(odir + white + uria), data = df_noo, family = binomial)
summary(test.glm)
xtable(summary(test.glm)$coefficients, digits=3)

# plot deviance residuals of test.glm
res_deviance <- residuals(test.glm, type = 'deviance')

neg_res <- res_deviance[res_deviance < 0]
pos_res <- res_deviance[res_deviance > 0]

ggplot(data.frame(res_deviance), aes(x = res_deviance)) +
  geom_histogram(binwidth = 0.1, fill = "steelblue", color = "black") +
  labs(x = "Deviance Residuals", y = "Count") +
  theme_bw()

# Cook's Distance
cooksdf <- as.data.frame(cooks.distance(test.glm))
names(cooksdf) <- "cooksd"
cooksdf$approved <- as.factor(df_noo$approved)

cutoff  <- round(8/(nrow(df_noo) - 2 * length(test.glm$coefficients)), 4)

plot1 <- ggplot(cooksdf, aes(x = seq(1:length(cooksd)), y = cooksd, col = approved)) +
  geom_point() +
  labs(x = "Observation", y = "Cook's Distance")

plot1 + geom_hline(aes(yintercept=cutoff)) +
  scale_y_continuous(breaks=sort(c(ggplot_build(plot1)$layout$panel_ranges[[1]]$y.major_source, cutoff))) +
  theme_bw()

# Total exceeding cutoff
cat('exceeding cutoff',cooksdf$approved[cooksdf$cooksd > cutoff] %>% table(), '\n')

# Approved distribution ratio
cat('approved ratio', df_noo$approved %>% table() %>% prop.table(), '\n')
```
